{{- if .Values.gui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mender-gui
  namespace: {{ .Release.Namespace }}
  labels:
    run: mender-gui
    app.kubernetes.io/name: mender-gui
    {{- include "mender.labels" . | nindent 4 }}
spec:
  progressDeadlineSeconds: 600
  {{- if not .Values.gui.autoscaling.enabled }}
  replicas: {{ .Values.global.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      run: mender-gui
  {{- with .Values.gui.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.gui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        run: mender-gui
    spec:
      {{- with .Values.gui.affinity }}
      affinity: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
{{- if .Values.global.s3.AWS_SERVICE_ACCOUNT_NAME }}
      serviceAccountName: {{ .Values.global.s3.AWS_SERVICE_ACCOUNT_NAME }}
{{- end }}
      containers:
      - name: mender-gui
        image: {{ .Values.gui.image.registry }}/{{ .Values.gui.image.repository }}:{{ .Values.gui.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.gui.image.imagePullPolicy }}
        resources:
{{ toYaml .Values.gui.resources | indent 10 }}
        readinessProbe:
          periodSeconds: 15
          tcpSocket:
            port: 80
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 80
        env:
        - name: INTEGRATION_VERSION
          value: {{ .Values.gui.env.INTEGRATION_VERSION | quote }}
        - name: MENDER_VERSION
          value: {{ .Values.gui.env.MENDER_VERSION | quote }}
        - name: MENDER_ARTIFACT_VERSION
          value: {{ .Values.gui.env.MENDER_ARTIFACT_VERSION | quote }}
        {{- if .Values.global.hosted }}
        - name: MENDER_HOSTED
          value: {{ .Values.global.hosted | quote }}
        {{- end }}
        {{- if .Values.global.enterprise }}
        - name: HAVE_ENTERPRISE
          value: {{ .Values.global.enterprise | quote }}
        - name: HAVE_MULTITENANT
          value: {{ .Values.global.enterprise | quote }}
        {{- end }}
        {{- if and .Values.auditlogs.enabled .Values.global.enterprise }}
        - name: HAVE_AUDITLOGS
          value: "true"
        {{- end }}
        {{- if .Values.deviceconnect.enabled }}
        - name: HAVE_DEVICECONNECT
          value: "true"
        {{- end }}
        {{- if .Values.deviceconfig.enabled }}
        - name: HAVE_DEVICECONFIG
          value: "true"
        {{- end }}
        {{- if and .Values.devicemonitor.enabled .Values.global.enterprise }}
        - name: HAVE_MONITOR
          value: "true"
        {{- end }}
        - name: TRACKER_CODE
          value: {{ .Values.gui.env.TRACKER_CODE }}
        - name: HAPPYFOX_KEY
          value: {{ .Values.gui.env.HAPPYFOX_KEY }}
        - name: STRIPE_API_KEY
          valueFrom:
            secretKeyRef:
              key: STRIPE_API_KEY_PK
              name: stripe-customers-rw
        - name: RECAPTCHA_SITE_KEY
          valueFrom:
            secretKeyRef:
              key: RECAPTCHA_SITE_KEY
              name: mender-recaptcha
        envFrom:
        - configMapRef:
            name: mender-gateway-address
      imagePullSecrets:
      - name: docker-hub-secret
{{- with .Values.gui.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
{{- end }}
{{- end }}
